### PR TITLE
add guarded for eloquent trick

### PR DESCRIPTION
**Pull request by aprian1337**
i have added $guarded for eloquent trick, please review

### CODE REVIEW

**Comment by syofyanzuhad** [comment]
thanks about that, do you want send pr for hacktoberfest?
(if you've register it, I'll add a `hacktoberfet` label)

**Comment by aprian1337** [comment]
> thanks about that, do you want send pr for hacktoberfest? (if you've register it, I'll add a `hacktoberfet` label)

yes, that's right

**Comment by aprian1337** [comment]
Thank you!

**Comment by syofyanzuhad** [comment]
> Thank you!

no problem, I should be the one thanking you 😅

**Pull request merged**
